spring.application.name=SpringBoot_JPA_Sort_Search_Paging
#Config Datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_search_sort_page_cntt2?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234$

#Config JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true